services:
  mysql:
    image: mysql:8
    container_name: bunary-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bunary
    ports: [3307:3306]
    volumes: [mysql-data:/var/lib/mysql]

  app:
    build: .
    container_name: bunary-app
    ports: [8080:8080]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bunary?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    depends_on: [mysql]

volumes:
  mysql-data: